const {test}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const {loader}=require('./loader.cjs'),root=path.join(__dirname,'..');
function queue(fetch){const store=new Map();const l=loader(root,{}, {},{window:{localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)}},fetch});return{...l,queue:l.load('src/lib/corporate-queue.ts'),entries:()=>JSON.parse([...store.values()][0]||'[]')}}
const item={code:'TEST',machineId:'a',productName:'Test',productPrice:3.5};
test('enqueue while flushing preserves later purchase',async()=>{let release;const q=queue(()=>new Promise(resolve=>release=()=>resolve({ok:true,json:async()=>({ok:true,valid:true})})));q.queue.enqueueRedemption(item);const p=q.queue.flushRedemptions();const second=q.queue.enqueueRedemption(item);release();await p;assert.equal(q.entries().length,1);assert.equal(q.entries()[0].idempotencyKey,second)});
test('offline entries survive more than twelve retries',async()=>{const q=queue(async()=>{throw Error('offline')});q.queue.enqueueRedemption(item);for(let n=0;n<15;n++)await q.queue.flushRedemptions();assert.equal(q.entries().length,1);assert.equal(q.entries()[0].attempts,15)});
test('business rejection retained for reconciliation rather than discarded',async()=>{const q=queue(async()=>({ok:true,json:async()=>({ok:true,valid:false,error:'Limit exceeded'})}));q.queue.enqueueRedemption(item);await q.queue.flushRedemptions();assert.equal(q.entries()[0].rejected,'Limit exceeded')});
test('fixed and percentage basket discounts use same dollar units as Fleet',()=>{const file=path.join(root,'src/components/cart-panel.tsx'),source=fs.readFileSync(file,'utf8'),ast=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let expression;const walk=n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='discount')expression=n.initializer.getText(ast);ts.forEachChild(n,walk)};walk(ast);assert.equal(vm.runInNewContext(expression,{subtotal:7,appliedPromo:{discountType:'fixed',discountValue:1.5}}),1.5);assert.equal(vm.runInNewContext(expression,{subtotal:8,appliedPromo:{discountType:'percent',discountValue:25}}),2)});
test('same purchase identity is queued only once',()=>{const q=queue(async()=>{throw Error('offline')});q.queue.enqueueRedemption({...item,idempotencyKey:'basket:product:0'});q.queue.enqueueRedemption({...item,idempotencyKey:'basket:product:0'});assert.equal(q.entries().length,1)});
test('corporate basket subsidy uses per-unit cents consistent with employer invoicing',()=>{const file=path.join(root,'src/components/cart-panel.tsx'),source=fs.readFileSync(file,'utf8'),ast=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let expression;const walk=n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='discount')expression=n.initializer.getText(ast);ts.forEachChild(n,walk)};walk(ast);assert.equal(vm.runInNewContext(expression,{subtotal:7.02,cartItems:[{price:3.51,orderQuantity:2}],appliedPromo:{kind:'corporate',discountValue:50}}),3.52)});
